sonar.projectKey=acst352_03-gifs-app-dev-talles
sonar.projectName=03-gifs-app-dev-talles
sonar.organization=oekwpd

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/03-gifs-app/lcov.info

sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/node_modules/**,\
  **/.angular/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/public/**

sonar.test.exclusions=\
  **/node_modules/**,\
  **/.angular/**,\
  **/dist/**
