#!/usr/bin/env node
// Generates src/environments/environment.<mode>.generated.ts with the Giphy
// API key inlined as a string literal, so the app never depends on
// `import.meta.env` at runtime (the @angular/build esbuild builder does not
// populate it from .env files the way plain Vite does — only Vitest does).
//
// Usage: node scripts/inject-env.cjs <development|production>
const fs = require('node:fs');
const path = require('node:path');

const mode = process.argv[2];
if (mode !== 'development' && mode !== 'production') {
  console.error('[inject-env] Usage: node scripts/inject-env.cjs <development|production>');
  process.exit(1);
}

// Load .env into process.env without overriding variables already set
// (CI/CD secrets and platform env vars always win over the local .env file).
const envFile = path.resolve(__dirname, '..', '.env');
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, 'utf8').split('\n')) {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (!match) continue;
    const key = match[1];
    let value = (match[2] ?? '').trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) {
      process.env[key] = value;
    }
  }
}

const apiKey = process.env.VITE_GIPHY_API_KEY ?? '';
if (!apiKey) {
  console.error('[inject-env] Missing VITE_GIPHY_API_KEY environment variable.');
  console.error('[inject-env] Set it in .env (local dev, see .env.example) or in your CI/CD platform (Vercel, GitHub Actions, etc.).');
  process.exit(1);
}

const outFile = path.resolve(__dirname, '..', 'src', 'environments', `environment.${mode === 'production' ? 'prod' : mode}.generated.ts`);

const content = `// AUTO-GENERATED by scripts/inject-env.cjs — DO NOT EDIT
// Source of truth: VITE_GIPHY_API_KEY env var (from .env locally, or the deployment platform).
// This file is gitignored; regenerating it does not change any tracked file.

export const environment = {
  production: ${mode === 'production'},
  companyName: 'Gifs',
  companyName2: 'App',
  companySlogan: 'Maneja tus gifs',

  giphyApiKey: ${JSON.stringify(apiKey)},
  giphyUrl: 'https://api.giphy.com/v1',
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, 'utf8');
console.log(`[inject-env] Wrote ${path.relative(process.cwd(), outFile)}`);
